sonar.projectKey=PipelineOnGitHub
sonar.organization=somsakgithub
sonar.branch.name=main

sonar.sources=PipelineOnGitHub
sonar.tests=PipelineOnGitHubTests,PipelineOnGitHubUITests

sonar.exclusions=**/*Tests/**,**/*.xcassets/**,**/Assets.xcassets/**

sonar.swift.swiftlint.reportPaths=swiftlint.log
sonar.swift.swiftformat.reportPaths=swiftformat.log

sonar.c.file.suffixes=.c,.h
sonar.cpp.file.suffixes=.cpp,.hpp,.cc
sonar.objc.file.suffixes=.m,.mm
sonar.swift.file.suffixes=.swift
